[project]
version = "1.0.18"
name = "sodium"
cincludes = []
cobjects = []
pkgconfig = ["libsodium.pc"]
cflags = []
lflags = []

[variants]
default = []

[dependencies]
err = "*"
hex = "*"
log = "*"
mem = "*"
project = "*"
slice = "*"

[repos]
project = "git://github.com/zzmodules/project"
